{pkgs, ...}: {
  imports = [
    ./ai.nix
    ./anime.nix
    ./api.nix
    ./archive.nix
    ./c.nix
    ./crypto.nix
    ./db.nix
    ./docker.nix
    ./emoji.nix
    ./gnome.nix
    ./media.nix
    ./myPkgs.nix
    ./mpv.nix
    ./network.nix
    ./nix.nix
    ./pkg.nix
    ./python.nix
    ./sec.nix
    ./sim.nix
    ./terminal.nix
    ./text.nix
    ./torrents.nix
  ];
  home.packages = with pkgs; [
    cacert
    cachix
    calibre
    coursier
    fishPlugins.bobthefish
    fishPlugins.foreign-env
    microsoft-edge
    monaspace
    nickel
    nushell
    nushellPlugins.highlight
    nyancat
    pandoc
    pnpm
    sccache
    stack
    tiv
    translate-shell
    translatelocally
    wl-clipboard-x11
  ];
}
