[ # 1
  "alertmanager"  # 2
  "avahi"  # 3
  "cadvisor"  # 4
  "calibreServer"  # 5
  "calibreWeb"  # 6
  "coredns"  # 7
  "corednsProm" # 8
  "grafana"  # 9
  "jellyfinHttp"  # 10
  "jellyfinHttps"  # 11
  "lokiGrpc"  # 12
  "lokiHttp"  # 13
  "nodeExporter"  # 14
  "ollama"  # 15
  "prometheus"  # 16
  "promtailGrpc"  # 17
  "promtailHttp"  # 18
  "qbittorrentWeb"  # 19
  "squidProxy"  # 20
  "squidTlsBump"  # 21
] # 22
